MONGODB_HOST: mongodb-{{ env }}.bongu.online
REDIS_HOST: redis-{{ env }}.bongu.online
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.bongu.online
CART_HOST: cart.backend-alb-{{ env }}.bongu.online
USER_HOST: user.backend-alb-{{ env }}.bongu.online
RABBITMQ_HOST: rabbitmq-{{ env }}.bongu.online
MYSQL_HOST: mysql-{{ env }}.bongu.online
SHIPPING_HOST: shipping.backend-alb-{{ env }}.bongu.online
PAYMENT_HOST: payment.backend-alb-{{ env }}.bongu.online